## Longest Palindromic Substring

In [17]:
class Solution:
    def longestPalindrome(self, s):
        """
        :type s: str
        :rtype: str
        """
        list_len = len(s)
        max_len = start = end = 0
        import numpy as np
        dp = np.zeros((list_len, list_len))
        for j in range(list_len):
            for i in range(j+1):
                if (j==i) or (j==i+1 and s[i]==s[j]) or (j>i+1 and s[i]==s[j] and dp[i+1][j-1]==1):
                    dp[i][j]=1
                    if j-i+1 > max_len:
                        max_len = j-i+1
                        start = i
                        end = j
        return s[start:end+1]
                    

In [18]:
solution = Solution()
solution.longestPalindrome("babad")

[[ 1.  0.  1.  0.  0.]
 [ 0.  1.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]] 3


'bab'

## Length of Last Word

In [1]:
class Solution:
    def lengthOfLastWord(self, s):
        """
        :type s: str
        :rtype: int
        """
        end = len(s)-1
        while end>=0 and s[end]==' ':
            end -= 1
        begin=end
        while begin>=0 and s[begin]!=' ':
            begin-=1
        return end-begin

## Isomorphic Strings 

In [5]:
class Solution:
    def isIsomorphic(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: bool
        """
        list_len = len(s)
        if list_len != len(t):
            return False
        MAX_CHARS = 256
        marked = [False]*256
        st_map = [-1]*256
        for index in range(list_len):
            if st_map[ord(s[index])] == -1:
                if marked[ord(t[index])]:
                    return False
                marked[ord(t[index])] = True
                st_map[ord(s[index])] = t[index]
            else:
                if st_map[ord(s[index])] != t[index]:
                    return False
        
        return True
                
                

In [6]:
x = list(range(10))
y = list(range(20, 30))

In [10]:
import collections

In [11]:
x = 'abcde'
y = 'bcdeacb'

In [12]:
s_1 = collections.Counter(x)
s_2 = collections.Counter(y)

In [13]:
s_1, s_2

(Counter({'a': 1, 'b': 1, 'c': 1, 'd': 1, 'e': 1}),
 Counter({'b': 2, 'c': 2, 'd': 1, 'e': 1, 'a': 1}))

97