## Longest Palindromic Substring

In [17]:
class Solution:
    def longestPalindrome(self, s):
        """
        :type s: str
        :rtype: str
        """
        list_len = len(s)
        max_len = start = end = 0
        import numpy as np
        dp = np.zeros((list_len, list_len))
        for j in range(list_len):
            for i in range(j+1):
                if (j==i) or (j==i+1 and s[i]==s[j]) or (j>i+1 and s[i]==s[j] and dp[i+1][j-1]==1):
                    dp[i][j]=1
                    if j-i+1 > max_len:
                        max_len = j-i+1
                        start = i
                        end = j
        return s[start:end+1]
                    

In [18]:
solution = Solution()
solution.longestPalindrome("babad")

[[ 1.  0.  1.  0.  0.]
 [ 0.  1.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]] 3


'bab'

## Length of Last Word

In [1]:
class Solution:
    def lengthOfLastWord(self, s):
        """
        :type s: str
        :rtype: int
        """
        end = len(s)-1
        while end>=0 and s[end]==' ':
            end -= 1
        begin=end
        while begin>=0 and s[begin]!=' ':
            begin-=1
        return end-begin

## Isomorphic Strings 

In [5]:
class Solution:
    def isIsomorphic(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: bool
        """
        list_len = len(s)
        if list_len != len(t):
            return False
        MAX_CHARS = 256
        marked = [False]*256
        st_map = [-1]*256
        for index in range(list_len):
            if st_map[ord(s[index])] == -1:
                if marked[ord(t[index])]:
                    return False
                marked[ord(t[index])] = True
                st_map[ord(s[index])] = t[index]
            else:
                if st_map[ord(s[index])] != t[index]:
                    return False
        
        return True
                
                

## Find and Replace Pattern

In [8]:
class Solution(object):
    def findAndReplacePattern(self, words, pattern):
        """
        :type words: List[str]
        :type pattern: str
        :rtype: List[str]
        """

        def findAndReplaceHelp(word, pattern):
            state_dic = {}
            if len(word) != len(pattern):
                return False
            for index, key_ch in enumerate(word):
                keys = state_dic.keys()
                if key_ch in keys:
                    if state_dic[key_ch] != pattern[index]:
                        return False
                else:
                    state_dic[key_ch] = pattern[index]
            values = state_dic.values()
            if len(values) != len(set(values)):
                return False
            return True

        result = []
        for word in words:
            if findAndReplaceHelp(word, pattern):
                result.append(word)
        return result

            
        
test_str_list = ["abc","deq","mee","aqq","dkd","ccc"]
pattern = "abb"
print(Solution().findAndReplacePattern(test_str_list, pattern))
                    

['mee', 'aqq']


## Find the Closest Palindrome 

In [36]:
import math
import sys
class Solution(object):
    def nearestPalindromic(self, n):
        """
        :type n: str
        :rtype: str
        """
        size = len(n)
        if size==1:
            return str(int(n)-1)
        
        result = []
        result.append('9'*(size-1))
        result.append('1'+'0'*(size-1)+'1')
        odd_reverse = lambda x:x+x[::-1][1:]
        even_reverse = lambda x:x+x[::-1]
        middle = math.ceil(size/2)
        pre_half_num = n[:middle]
        
        if size%2 == 0:
            print('even: ',pre_half_num, even_reverse(pre_half_num))
            result.append(even_reverse(pre_half_num))
            result.append(even_reverse(str(int(pre_half_num)-1)))
            result.append(even_reverse(str(int(pre_half_num)+1)))
        else:
            print('odd: ', pre_half_num, odd_reverse(pre_half_num))
            result.append(odd_reverse(pre_half_num))
            result.append(odd_reverse(str(int(pre_half_num)-1)))
            result.append(odd_reverse(str(int(pre_half_num)+1)))
            
        def get_distance(num, target):
            return abs(int(num) - int(target))
        
        min_distance = sys.maxsize
        result_index = -1
        for index, num_str in enumerate(result):
            distance = get_distance(num_str, n)
            if (distance !=0 and distance<min_distance) or (distance==min_distance and int(num_str)<int(result[result_index])):
                result_index = index
                min_distance = distance
        
        return result[result_index]