## 换钱的最少币数

In [14]:
import sys
def get_least_coin(nums, target):
    states = [0 for x in range(target+1)]
    for x in range(1, target+1):
        min_num = sys.maxsize
        for coin in nums:
            pre_num = x-coin
            if pre_num>=0:
                 min_num = min(states[pre_num]+1, min_num)
        states[x] = min_num
    return states

In [51]:
test_array = []
def iterate_test():
    for i in range(10):
        yield i
        print(i)


## 最长递增序列

In [124]:
def getLTS(nums):
    def binary_search(ends, num):
        left, right = 0, len(ends)-1
        while left<right:
            middle = int((left+right)/2)
            if num<ends[middle]:
                right = middle - 1
            elif num>ends[middle]:
                left = middle + 1
            else:
                return middle
        return left
    def generate_dp(nums):
        ends = [nums[0]]
        dp = []
        for i in range(len(nums)):
            index = binary_search(ends, nums[i])
            if index+1>len(ends):
                ends.append(nums[i])
            elif index==0 and nums[i]<ends[0]:
                ends[0]==nums[i]
            else:
                ends[index+1] = nums[i]
            dp[i].append(index+1)
        return dp

In [126]:
def binary_search(ends, num):
    left, right = 0, len(ends)-1
    while left<=right:
        middle = int((left+right)/2)
        if num<ends[middle]:
            right = middle - 1
        else:
            left = middle + 1
    return left
def generate_dp(nums):
    ends = [nums[0]]
    dp = [1]
    for i in range(1, len(nums)):
        index = binary_search(ends, nums[i])
        if index==len(ends):
            ends.append(nums[i])
        else:
            ends[index] = nums[i]
        dp.append(index+1)
        print('index: ', index, " ends: ", ends, " dp: ", dp)
    return dp


## 汉诺塔

In [129]:
def move(n, start, mid, end):
    if n==1:
        print("move from {} to {}".format(start, end))
    else:
        move(n-1, start, end, mid)
        move(1, start, mid, end)
        move(n-1, mid, start, end)
move(3, 'start', 'mid', 'end')

move from start to end
move from start to mid
move from end to mid
move from start to end
move from mid to start
move from mid to end
move from start to end


## 最长公共子序列

In [35]:
def get_longest_dp(str1, str2):
    m, n = len(str1), len(str2)
    dp = [[0 for j in range(n)] for i in range(m)]
    dp[0][0] = 1 if str1[0]==str2[0] else 0
    for i in range(1, m):
        dp[i][0]=max(dp[i-1][0], 1 if str1[i]==str2[0] else 0)
    for j in range(1, n):
        dp[0][j]=max(dp[0][j-1], 1 if str2[j]==str1[0] else 0)
    for i in range(1, m):
        for j in range(1, n):
            dp[i][j]=max(dp[i-1][j], dp[i][j-1])
            if str1[i]==str2[j]:
                dp[i][j]=max(dp[i][j], dp[i-1][j-1]+1)
    return dp

def get_longest_str(str1, str2, dp):
    i=len(str1)-1
    j=len(str2)-1
    m=dp[i][j]
    result_str = ''
    while m>0:
        if i>0 and (dp[i-1][j]==dp[i][j]):
            i-=1
        elif j>0 and (dp[i][j-1]==dp[i][j]):
            j-=1
        else:
            result_str=str1[i]+result_str
            i-=1
            j-=1
            m-=1
    return result_str
            

## 最长公共子串

In [42]:
def get_longest_common_str(str1, str2):
    m, n = len(str1), len(str2)
    dp = [[0 for j in range(n)] for i in range(m)]
    for i in range(m):
        if str1[i]==str2[0]:
            dp[i][0]=1
    for j in range(n):
        if str1[0]==str2[j]:
            dp[0][j]=1
    for i in range(1, m):
        for j in range(1, n):
            if str1[i]==str2[j]:
                dp[i][j]=dp[i-1][j-1]+1
    return dp

In [43]:
get_longest_common_str('abcde', 'bebcd')

[[0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0],
 [0, 0, 0, 2, 0],
 [0, 0, 0, 0, 3],
 [0, 1, 0, 0, 0]]

## 最小编辑代价

In [55]:
def change_cost(str1, str2, costs):
    m = len(str1)
    n = len(str2)
    dp = [[0 for j in range(n+1)] for i in range(m+1)]
    for j in range(n+1):
        dp[0][j]=j*costs[0]
    for i in range(m+1):
        dp[i][0]=i*costs[1]
    for i in range(1, m+1):
        for j in range(1, n+1):
            if str1[i-1]==str2[j-1]:
                dp[i][j]=dp[i-1][j-1]
            else:
                dp[i][j]=dp[i-1][j-1]+costs[2]
            dp[i][j] = min(dp[i-1][j]+costs[1], dp[i][j-1]+costs[0], dp[i][j])
            
    return dp

In [56]:
str1 = 'ab12cd3'
str2 = 'abcdf'
costs = [5, 3, 2]
change_cost(str1, str2, costs)

[[0, 5, 10, 15, 20, 25],
 [3, 0, 5, 10, 15, 20],
 [6, 3, 0, 5, 10, 15],
 [9, 6, 3, 2, 7, 12],
 [12, 9, 6, 5, 4, 9],
 [15, 12, 9, 6, 7, 6],
 [18, 15, 12, 9, 6, 9],
 [21, 18, 15, 12, 9, 8]]

## 字符串的交错组成 

In [59]:
def is_cross(str1, str2, target):
    if str1 is None or (str2 is None) or (target is None):
        return False
    m = len(str1)
    n = len(str2)
    dp = [[False for j in range(n+1)] for i in range(m+1)]
    dp[0][0] = True
    for i in range(1, m+1):
        if str1[i-1]!=target[i-1]:
            break
        dp[i][0] = True
    
    for j in range(1, n+1):
        if str2[j-1]!=target[j-1]:
            break
        dp[0][j]=True
    
    for i in range(1, m+1):
        for j in range(1, n+1):
            if str1[i-1]==target[i+j-1] and dp[i-1][j]:
                dp[i][j] = True
            elif str2[j-1]==target[i+j-1] and dp[i][j-1]:
                dp[i][j] = True
    return dp
        

In [61]:
str1 = 'AB'
str2 = '12'
target = 'AB12'
is_cross(str1, str2, target)


[[True, False, False], [True, False, False], [True, True, True]]

## 骑士问题

In [82]:
def get_least(number_map):
    m, n = len(number_map), len(number_map[0])
    dp = [[0 for j in range(n)] for i in range(m)]
    dp[m-1][n-1] = max(1, 1-number_map[m-1][n-1])
    
    i, j = m-2, n-2
    while i>=0:
        dp[i][n-1] = max(1, dp[i+1][n-1]-number_map[i][n-1])
        i-=1

    while j>=0:
        dp[m-1][j] = max(1, dp[m-1][j+1]-number_map[m-1][j])

        j-=1
    
    i=m-2
    while i>=0:
        j=n-2
        while j>=0:
            right = max(1, dp[i][j+1]-number_map[i][j])
            down = max(1, dp[i+1][j]-number_map[i][j])
            dp[i][j] = min(right, down)
#             print('{}{}: {}'.format(i, j, dp[i][j]))
            j-=1
        i-=1
        
    return dp

In [83]:
number_map=[[-2, -3, 3],[-5, -10, 1],[0, 30, -5]]
get_least(number_map)

[[7, 5, 2], [6, 11, 5], [1, 1, 6]]

## 表达式得到期望结果的种数

In [48]:
import numpy as np
def get_kind_number(express, desired):
    str_len = len(express)
    t_array = np.zeros((str_len, str_len))
    f_array = np.zeros((str_len, str_len))
    t_array[0][0] = 1 if express[0]=='1' else 0
    f_array[0][0] = 1 if express[0]=='0' else 0
    i=2
    while i<str_len:
        t_array[i][i] = 1 if express[i]=='1' else 0
        f_array[i][i] = 1 if express[i]=='0' else 0
        
        j=i-2
        while j>=0:
            k=j
            while k<i:
                if express[k+1]=='&':
                    t_array[j][i]+=t_array[j][k]*t_array[k+2][i]
                    f_array[j][i]+=f_array[j][k]*(f_array[k+2][i]+t_array[k+2][i])+t_array[j][k]*f_array[k+2][i]
                elif express[k+1]=='|':
                    f_array[j][i]+=f_array[j][k]*f_array[k+2][i]
                    t_array[j][i]+=t_array[j][k]*(f_array[k+2][i]+t_array[k+2][i])+f_array[j][k]*f_array[k+2][i]
                elif express[k+1]=='^':
                    t_array[j][i]+=(t_array[j][k]*f_array[k+2][i]+f_array[j][k]*t_array[k+2][i])
                    
                    f_array[j][i]+=(t_array[j][k]*t_array[k+2][i]+f_array[j][k]*f_array[k+2][i])
                if i==4 and j==0:
                        print(f_array[j][i], k, f_array[j][k], f_array[k+2][i], express[j:i+1], express[k+1])
                k+=2
#             print(f_array[j][i], express[j:i+1], j, i)
            j-=2
        i+=2
    print(t_array)
    print(f_array)
    return t_array[0][str_len-1] if desired else f_array[0][str_len-1]

In [49]:
get_kind_number('1^0|0|1', False)

1.0 0 0.0 1.0 1^0|0 ^
1.0 2 0.0 1.0 1^0|0 |
[[1. 0. 1. 0. 2. 0. 2.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


1.0

In [5]:
from pymongo import MongoClient

In [6]:
client = MongoClient()

In [8]:
client['test']['Colletion']

Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'test'), 'Colletion')