## Longest Palindromic Substring

In [17]:
class Solution:
    def longestPalindrome(self, s):
        """
        :type s: str
        :rtype: str
        """
        list_len = len(s)
        max_len = start = end = 0
        import numpy as np
        dp = np.zeros((list_len, list_len))
        for j in range(list_len):
            for i in range(j+1):
                if (j==i) or (j==i+1 and s[i]==s[j]) or (j>i+1 and s[i]==s[j] and dp[i+1][j-1]==1):
                    dp[i][j]=1
                    if j-i+1 > max_len:
                        max_len = j-i+1
                        start = i
                        end = j
        return s[start:end+1]
                    

In [18]:
solution = Solution()
solution.longestPalindrome("babad")

[[ 1.  0.  1.  0.  0.]
 [ 0.  1.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]] 3


'bab'

## Length of Last Word

In [ ]:
class Solution:
    def lengthOfLastWord(self, s):
        """
        :type s: str
        :rtype: int
        """
        end = len(s)-1
        while end>=0 and s[end]==' ':
            end -= 1
        begin=end
        while begin>=0 and s[begin]!=' ':
            begin-=1
        return end-begin